### PR TITLE
The Doctor

### LINKED ISSUE #297: @babel/polyfill polyfills resolve to wrong `core-js` version on compile time
This issue is a follow-up of https://github.com/xing/hops/pull/819.

@untool/webpack relies on [`@babel/present-env`'s `useBuiltIns` feature](https://babeljs.io/docs/en/babel-preset-env#usebuiltins) which [might break](https://babeljs.io/docs/en/babel-preset-env#usebuiltins-entry) when the globally hoisted `core-js` version doesn't match the one expected by `@babel/polyfill`.

## Solution 1: `core-js` as peer dependency
A solution might consist of declaring `core-js@^2` as `@untool/webpack`'s peer dependency to force the consuming application to keep it as it's own direct dependency

## Solution 2: `core-js v2` dependency check on build
On compile time`@untool/webpack` might ensure that the expected version of `core-js` is available at `node_modules` root and issue a warning message if not.

## Solution 3: custom module resolution
Extend the current custom module resolution to target the polyfill declaration injected by babel and redirect them to the expected `core-js` library.

### PR DESCRIPTION
**Pull request by dmbch**
In this PR, I am proposing to introduce a dedicated `@untool/info` package. This package will contain an improved logger (extracted from `@untool/yargs`) and a hook and helpers to run preflight checks.

This branch is based on the `modular-logging` branch as proposed in #298 and closes #297.

### CODE REVIEW

File: packages/info/lib/doctor.js [hunk 1]
```diff
@@ -0,0 +1,27 @@
+'use strict';
+
+const define = require('mixinable');
+
+const {
+  sync: { callable: callable, sequence },
```
Comment (jhiode) [inline packages/info/lib/doctor.js]: Could be just `{ callable, sequence }`

File: packages/info/lib/doctor.js [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+} = define;
+
+const strategies = {
+  diagnoseConfig: callable,
+  diagnoseDuplicatePackages: callable,
+  diagnoseInvalidPackages: callable,
```
Comment (jhiode) [inline packages/info/lib/doctor.js]: So only the doctor can do the diagnose? (I'm asking because the strategy is callable or a.k.a override).

And do we also want to provide a check to make sure all packages of a specific workspace (like `@untool/*` or `hops-*`) have the same version in common?

File: packages/info/lib/doctor.js [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+  submitDiagnosis: callable,
+  getDiagnoses: (...args) => {
+    return sequence(...args).then((results) => [].concat(...results));
+  },
+  logDiagnoses: sequence,
```
Comment (jhiode) [inline packages/info/lib/doctor.js]: Should we name this `inspectDiagnoses`? Because logging is only one way of handling it, right?

File: packages/info/mixins/doctor/mixin.core.js [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+  }
+  diagnose({ diagnoseConfig, diagnoseDuplicatePackages }) {
+    diagnoseConfig();
+    diagnoseDuplicatePackages('@untool/*');
+  }
+  bootstrap() {
+    const { doctor } = this;
+    return this.diagnose(doctor).then((results) =>
+      doctor.submitDiagnosis(
+        ...[].concat(...results.filter((result) => result !== undefined))
```
Comment (jhiode) [inline packages/info/mixins/doctor/mixin.core.js]: Why can't we just write `...results.filter((result) => result !== undefined)`?

File: packages/info/lib/doctor.js (hunk 2 above)
Comment (dmbch) [reply packages/info/lib/doctor.js]: There is no way for anything to actually override strategies/implementations in this context, so yes, it is only this very implementation.

I would very much like to add a check like the one you describe, but maybe after merging this PR?

File: packages/info/lib/doctor.js (hunk 3 above)
Comment (dmbch) [reply packages/info/lib/doctor.js]: I thought about that, too - but, once again, all current diagnoses only log, and I would want to keep it that way.

File: packages/info/mixins/doctor/mixin.core.js (hunk 4 above)
Comment (dmbch) [reply packages/info/mixins/doctor/mixin.core.js]: Because we must expect the individual results to arrays, so we would get an array of arrays if we did what you propose. We need to flatten that.

File: packages/info/README.md [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+
+### Installation
+
+```bash
+$ yarn add @untool/info # OR npm install @untool/info
+```
+
+## CLI
+
+`@untool/info` does not define any commands of its own, but only adds some global CLI flags to control console output. Using the flags `-v`/`--verbose` and `-q`/`--quiet` once or multiple times, you can de- and increase the log output. Default log level is `info`, passing a single `-q` will reduce it to `warning` while a single `-v` will bump it to `verbose`. Passing `-qqq` will silence all output completely.
```
[the remark this answers is not in the document]
Comment (dmbch) [reply packages/info/README.md]: I *think* it is... I know the `-qq` from [apt-get](https://linux.die.net/man/8/apt-get) and the `-vv` (and even `-vvv`) from [tcpdump](https://linux.die.net/man/8/tcpdump)...

File: packages/info/README.md [hunk 6]
```diff
@@ -0,0 +1,76 @@
+# `@untool/info`
+
+[![travis](https://img.shields.io/travis/untool/untool/master.svg)](https://travis-ci.org/untool/untool)&nbsp;[![npm](https://img.shields.io/npm/v/@untool%2Finfo.svg)](https://www.npmjs.com/package/@untool%2Finfo)
```
[the remark this answers is not in the document]
Comment (dmbch) [reply packages/info/README.md]: Absolutely true! Nice catch - I now fixed it in almost all our READMEs.
