### PR TITLE
Fix hot module reloading for Windows / Edge and Node 11.11.0

### LINKED ISSUE #311: Webpack: Signal based HMR crashes on windows
While initially running my app compiles just fine, however on editing any of the app's files, the watcher crashes:
```
untest:error TypeError [ERR_UNKNOWN_SIGNAL]: Unknown signal: SIGUSR2

at process.kill (internal/process/per_thread.js:193:15)

at Watching.compiler.watch [as handler] (.\node_modules\@untool\webpack\lib\middlewares\render.js:50:19)

at compiler.hooks.done.callAsync (.\node_modules\webpack\lib\Watching.js:98:9)

at AsyncSeriesHook.eval [as callAsync] (eval at create (.\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)

at Watching._done (.\node_modules\webpack\lib\Watching.js:97:28)

at compiler.emitRecords.err (.\node_modules\webpack\lib\Watching.js:72:19)

at Compiler.emitRecords (.\node_modules\webpack\lib\Compiler.js:449:39)

at compiler.emitAssets.err (.\node_modules\webpack\lib\Watching.js:53:20)

at hooks.afterEmit.callAsync.err (.\node_modules\webpack\lib\Compiler.js:435:14)

at AsyncSeriesHook.eval [as callAsync] (eval at create (.\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
```

The signal `SIGUSR2` is not defined in Windows environments. I'm not sure if there is a way to kill the process on windows by another call. Seems like we need to fallback to `webpack/hot/poll` on windows, as suggested here: https://github.com/sysgears/apollo-universal-starter-kit/issues/14

### PR DESCRIPTION
**Pull request by ZauberNerd**
This PR contains two parts - first it switches to using custom events instead of signals to make HMR work for the Node build, then it includes an EventSource polyfill to make HMR work in the browser.

Closes #311

### CODE REVIEW

File: packages/webpack/lib/configs/develop.js [hunk 1]
```diff
@@ -83,6 +83,7 @@ module.exports = function getConfig(config, name) {
     mode: 'development',
     context: config.rootDir,
     entry: [
+      require.resolve('../shims/event-source'),
```
Comment (dmbch) [inline packages/webpack/lib/configs/develop.js]: We can add the actual `eventsource` package here right away instead of adding another shim: it is being bundled anyway and will only attach itself to `window` if missing:

https://github.com/EventSource/eventsource/blob/82d38b0b0028ba92e861240eb6a943cbcafc8dff/lib/eventsource-polyfill.js#L5
